site:
  title: On Boarding
  brand:
    label: On Boarding
    image: /public/images/brand.png
  seo:
    robots: allow
    keywords: quart
    description: Chat and collaborative workspace based on Quart
    favicon: /public/images/favicon.ico
  theme: default
  themes:
    - default
  styles: ''
  scripts: ''
  copyright: 1998-2020 XAM
menus:
  util:
    - name: home
      path: /
      text: Home
      icon: fa fa-home
    - name: board
      path: /board
      text: Board
      icon: fa fa-board
  auth:
    - name: login
      path: /auth/login
      text: Login
      icon: fa fa-sign-in-alt
  info:
    - name: terms
      path: /terms
      text: Terms
      icon: fa fa-file
    - name: privacy
      path: /privacy
      text: Privacy
      icon: fa fa-key
  main: []
