DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL,
  `password` PASSWORD NOT NULL,
  `mail` TEXT NOT NULL
);
DROP TABLE IF EXISTS `post`;
CREATE TABLE `post` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `title` TEXT NOT NULL,
  `content` TEXT NOT NULL,
  `fk_u` INTEGER,
  FOREIGN KEY (fk_u) REFERENCES user(id)
);
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL
);
DROP TABLE IF EXISTS `user_role`;
CREATE TABLE `user_role` (
  `fk_r` INTEGER,
  `fk_u` INTEGER,
  FOREIGN KEY (fk_r) REFERENCES role(id)
  FOREIGN KEY (fk_u) REFERENCES user(id)
);
DROP TABLE IF EXISTS `node`;
CREATE TABLE `node` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `type` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `data` JSON NOT NULL,
  `fk_u` INTEGER,
  FOREIGN KEY (fk_u) REFERENCES user(id)
);
